# http://localhost:5001/config-application/dev/
# http://localhost:5001/config-application-prod.yml
# http://localhost:5001/config-application-prod.properties
spring:
  profiles:
    active: dev
---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: microservice-config-dev
---
server:
  port: 4002
spring:
  profiles: prod
  application:
    name: microservice-config-prod
