version: "3"
services:
  frontend:
    image: docker.io/konmyn/microservice:front-1.0.0
    volumes:
      - ./config/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on: 
      - zuul-gateway
  config-server:
    image: docker.io/konmyn/microservice:config-1.0.0
    restart: always
    volumes:
      - ./config/config-server/application.yml:/app/application.yml
      - ./config/config-server/config:/app/config/
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on: 
      - redis
  zuul-gateway:
    image: docker.io/konmyn/microservice:zuul-1.0.0
    volumes:
      - ./config/zuul/application.yml:/app/application.yml
    ports:
      - "7001:7001"
    depends_on: 
      - config-server
      - eureka
      - product
      - cart
      - order
      - user
  eureka:
    image: docker.io/konmyn/microservice:eureka-1.0.0
    restart: always
    volumes:
      - ./config/eureka/application.yml:/app/application.yml
      - ./config/eureka/bootstrap.yml:/app/bootstrap.yml
    ports:
      - "6001:6001"
    depends_on: 
      - config-server
  product:
    image: docker.io/konmyn/microservice:product-1.0.0
    volumes:
      - ./config/product/application.yml:/app/application.yml
      - ./config/product/bootstrap.yml:/app/bootstrap.yml
    depends_on: 
      - config-server
      - eureka
    ports:
      - "8080"
  cart:
    image: docker.io/konmyn/microservice:cart-1.0.0
    volumes:
      - ./config/cart/application.yml:/app/application.yml
      - ./config/cart/bootstrap.yml:/app/bootstrap.yml
    depends_on: 
      - config-server
      - eureka
    ports:
      - "8080"
  order:
    image: docker.io/konmyn/microservice:order-1.0.0
    volumes:
      - ./config/order/application.yml:/app/application.yml
      - ./config/order/bootstrap.yml:/app/bootstrap.yml
    depends_on: 
      - config-server
      - eureka
    ports:
      - "8080"
  user:
    image: docker.io/konmyn/microservice:user-1.0.0
    volumes:
      - ./config/user/application.yml:/app/application.yml
      - ./config/user/bootstrap.yml:/app/bootstrap.yml
    depends_on: 
      - config-server
      - eureka
    ports:
      - "8080"

  # 数据库服务
  mysqldb:
    image: docker.io/mysql:5.7.28
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    container_name: mysqldb
    hostname: mysqldb
    command:
      - --default-time_zone=+8:00
      - --explicit_defaults_for_timestamp
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/shanghai
    ports:
      - "3306:3306"
  rabbitmq:
    image: docker.io/rabbitmq:3.8.2
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmquser
      RABBITMQ_DEFAULT_PASS: rabbitmqpass
    ports:
      - "5672:5672"
    depends_on: 
      - mysqldb
  redis:
    image: docker.io/redis:5.0.7
    restart: always
    container_name: redis
    hostname: redis
    sysctls:
    - net.core.somaxconn=4096
    ports:
      - "6379:6379"
    depends_on: 
      - rabbitmq