version: "3"
services:
  mysqldb:
    image: harbor.beautytiger.com/docker.io/mysql:5.7.28
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    container_name: mysqldb
    hostname: mysqldb
    command:
      - --default-time_zone=+8:00
      - --explicit_defaults_for_timestamp
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/shanghai
    ports:
      - "3306:3306"
  rabbitmq:
    image: harbor.beautytiger.com/docker.io/rabbitmq:3.8.2
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmquser
      RABBITMQ_DEFAULT_PASS: rabbitmqpass
    ports:
      - "5672:5672"
  redis:
    image: harbor.beautytiger.com/docker.io/redis:5.0.7
    restart: always
    container_name: redis
    hostname: redis
    sysctls:
    - net.core.somaxconn=4096
    ports:
      - "6379:6379"
