server:
  port: 5001

spring:
  application:
    name: microservice-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
#      使用git
#        git:
#          uri: https://github.com/beautytiger/micro-tao.git
#          uri: https://github.com.cnpmjs.org/beautytiger/micro-tao.git
#          default-label: config
#          search-paths:
#          - config
