server:
  port: 6001 # 服务端口

eureka:
  instance:
    hostname: eureka01.beautytiger.com # eureka服务端的实例名称
#    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
#    ip-address: 192.168.28.6 #强制指定IP地址，默认会获取本机的IP地址
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版，多实例
#      defaultZone: http://eureka02.beautytiger.com:6002/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制